# Generated by Django 5.2.8 on 2025-12-09 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('totalExpenditure', models.IntegerField(default=0)),
                ('cumulativePoints', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('country', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TypeCustomer',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('minimumLevel', models.IntegerField()),
                ('maximumLevel', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeMedicine',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('startday', models.DateField(blank=True, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('sex', models.BooleanField(null=True)),
                ('salary', models.IntegerField(null=True)),
                ('did', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.department')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.position')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('dateOfcreate', models.DateField()),
                ('totalAmount', models.IntegerField(default=0)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.customer')),
                ('eid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('content', models.IntegerField(blank=True, null=True)),
                ('activeIngredient', models.CharField(blank=True, max_length=30, null=True)),
                ('inputTime', models.DateField(blank=True, null=True)),
                ('productionDate', models.DateField(blank=True, null=True)),
                ('expirationDate', models.DateField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=10, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('importPrice', models.IntegerField(default=0)),
                ('sellingPrice', models.IntegerField(default=0)),
                ('mid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.manufacturer')),
                ('tid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.typemedicine')),
            ],
        ),
        migrations.CreateModel(
            name='RollCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('months', models.IntegerField()),
                ('years', models.IntegerField()),
            ],
            options={
                'unique_together': {('months', 'years')},
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='tid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.typecustomer'),
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=10)),
                ('role', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('eid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.employee')),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseReceipt',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('inputDay', models.DateField(blank=True, null=True)),
                ('totalImport', models.IntegerField(default=0)),
                ('eid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.employee')),
            ],
        ),
        migrations.CreateModel(
            name='DetailedAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.DateField()),
                ('checkin', models.TimeField(blank=True, null=True)),
                ('checkout', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('eid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.employee')),
            ],
            options={
                'unique_together': {('eid', 'days')},
            },
        ),
        migrations.CreateModel(
            name='BillDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('unitPrice', models.IntegerField(default=0)),
                ('totalAmount', models.IntegerField(default=0)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.bill')),
                ('mid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.medicine')),
            ],
            options={
                'unique_together': {('bid', 'mid')},
            },
        ),
        migrations.CreateModel(
            name='SummaryAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numOfworkDay', models.IntegerField(default=0)),
                ('numOfdayOff', models.IntegerField(default=0)),
                ('netSalary', models.IntegerField(default=0)),
                ('eid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.employee')),
                ('rid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.rollcall')),
            ],
            options={
                'db_table': 'Summary_Attendance',
                'unique_together': {('rid', 'eid')},
            },
        ),
        migrations.CreateModel(
            name='WarehouseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('unitPrice', models.IntegerField()),
                ('totalAmount', models.IntegerField(blank=True, null=True)),
                ('mid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.medicine')),
                ('wid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.warehousereceipt')),
            ],
            options={
                'unique_together': {('wid', 'mid')},
            },
        ),
    ]
