# Generated by Django 5.2.8 on 2025-12-19 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='cid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.customer'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='dateOfcreate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='eid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.employee'),
        ),
        migrations.AlterField(
            model_name='billdetails',
            name='bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='myapp.bill'),
        ),
        migrations.AlterField(
            model_name='billdetails',
            name='mid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.medicine'),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='users',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterModelTable(
            name='users',
            table='myapp_users',
        ),
    ]
