# Generated by Django 5.2.8 on 2025-12-27 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('startday', models.DateTimeField(blank=True, null=True)),
                ('endday', models.DateTimeField(blank=True, null=True)),
                ('value', models.IntegerField()),
                ('tid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.typecustomer')),
            ],
        ),
    ]
