# Generated by Django 5.2.8 on 2025-12-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Tiền mặt'), ('transfer', 'Chuyển khoản')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='bill',
            name='id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
