# Generated by Django 5.2.8 on 2025-12-19 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_bill_cid_alter_bill_dateofcreate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='phone',
        ),
        migrations.AlterField(
            model_name='users',
            name='eid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='myapp.employee'),
        ),
    ]
